apiVersion: csdp.codefresh.io/v1
kind: ApplicationConfiguration
metadata:
  name: guestbook-ptemplate
spec:
  applicationSourceSelector:
    matchExpressions:
    - key: app.kubernetes.io/instance
      operator: Exists
  priority: 0
  versionSource:
    file: Chart.yaml
    jsonPaths: {"appVersion" }
  promotion:
    Chart.yaml:
      jsonPaths:
      - $.appVersion
      - $.version
    values.yaml:
      jsonPaths:
      - $..image
