apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: Guestbook
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/NimRegev/argocd-example-apps.git
    targetRevision: staging
  destination:
    name: in-cluster
    namespace: prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
